### PR TITLE
52 documentation on installation requires clarification for zsh 2

### LINKED ISSUE #52: Documentation on installation requires clarification for zsh
zsh uses square brackets for globbing, hence the command:
`bash
pip install .[dev]
`
in https://diamondlightsource.github.io/python3-pip-skeleton-cli/main/user/tutorials/new.html#getting-started-with-your-new-repo will fail with the error:
`bash
zsh: no matches found: .[dev]
`

The correct command is instead:
`bash
pip install '.[dev]'
`

This could/should use flagging as a possiblity in the documentation?

### PR DESCRIPTION
**Pull request by evalott100**
Simple change to documentation.
Closes #52

### CODE REVIEW

**Comment by evalott100** [comment]
We don't need to prepend with `bash` as in ` bash pip install '.[dev]' `. The `pip install '.[dev]' ` will work in both bash and zsh.

**Comment by coretl** [comment]
@evalott100 please can you make a corresponding change to the skeleton repo, then pull from there into the cli repo before applying these changes?

**Review by gilesknap — APPROVED** [review]
looks good

**Comment by evalott100** [comment]
Will pull pip3-python-skeleton after the change to the docs PR above is accepted.

**Pull request closed without merging**
